il_mode: CIL

dataset: clinc150_task15_numbertarget
classification_type: sentence-level

backbone_type: generative
backbone_extract_token: last_token

method: SEQ

lr: 1e-5
batch_size: 4

prompt_type: auto
