il_mode: IIL

dataset: concept_1k_task1

classification_type: auto

backbone_extract_token: last_token

classifier: None

Replay_batch_level: False

method: ICL
ICL_n_shot: 5

lr: 1e-5
info_per_steps: 25

prompt_type: auto