il_mode: CIL

dataset: clinc150_task15
classification_type: sentence-level

backbone_type: generative
backbone_extract_token: last_token

method: SEQ
SEQ_fix_old_classifier: True

lr: 1e-5
batch_size: 4

prompt_type: auto