il_mode: CIL

dataset: tacred_task8
classification_type: sentence-level

backbone_type: generative
backbone_extract_token: last_token

method: IPEFT
IPEFT_type: LoRA
IPEFT_fix_old_classifier: True
IPEFT_fix_old_peft: True

lr: 5e-4
batch_size: 4

prompt_type: auto