il_mode: CIL

dataset: fewnerd_task11_base6_inc6
classification_type: word-level

backbone_type: discriminative

method: PEFT
PEFT_type: PromptTuning
PEFT_prompt_tuning_init_text: none

prompt_type: none