il_mode: TIL

dataset: banking77_task7
classification_type: sentence-level

backbone_extract_token: cls_token
backbone_type: discriminative

method: PEFT
PEFT_type: PromptTuning

lr: 1e-5
batch_size: 4

prompt_type: none