il_mode: CIL

dataset: topic3datasets_task5
classification_type: sentence-level

backbone_type: discriminative
backbone_extract_token: cls_token

method: CLSER

lr: 1e-5
batch_size: 4

prompt_type: none