il_mode: TIL

dataset: banking77_task7
classification_type: sentence-level

backbone_type: generative
backbone_extract_token: last_token

method: SEQ
SEQ_fix_encoder: True

lr: 1e-5
batch_size: 4

prompt_type: auto