il_mode: CIL

dataset: ontonotes5_task6_base8_inc2
classification_type: word-level

backbone_type: discriminative

method: PEFT
PEFT_type: PromptTuning
PEFT_prompt_tuning_init_text: none

prompt_type: none