il_mode: CIL

dataset: ontonotes5_task6_base8_inc2
classification_type: word-level

backbone_type: discriminative

method: SEQ
SEQ_fix_old_classifier: True
SEQ_fix_encoder: True
SEQ_warmup_epoch_before_fix_encoder: 3
SEQ_warmup_target: ce-loss

prompt_type: none