il_mode: CIL

dataset: banking77_task7
classification_type: sentence-level

backbone_type: generative
backbone_extract_token: last_token

method: L2KD
LAMOL_use_task_specific_gen_token: True

lr: 1e-5
batch_size: 4

prompt_type: auto